/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   Fixed.hpp                                          :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: trpham <trpham@student.hive.fi>            +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/08/11 11:35:07 by trpham            #+#    #+#             */
/*   Updated: 2025/08/11 16:13:04 by trpham           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#pragma once

#include <iostream>

/* 
	Floating point number representation:
	number = (sign ? -1:1) * 2^(exponent) * 1.(mantissa bits) */

class Fixed
{
private:
	int					_rawValue;
	static const int	_fractionBit;
	
public:
	Fixed(void);
	~Fixed();
	
	/* copy constructor
	- default copy constructor == implicit copy constructor, generated by compiler: shallow copy of the data pointer.
	copy the address of the original data member
	- user-defined copy constructor == explicit copy constructor: to create a deep copy 
		. the const is optional but is added so that we do not modify the obj by mistake. 
		. we need to define our own copy constructor only if an object has pointers or 
		any runtime allocation of the resource like a file handle, a network connection, 
		etc because the default constructor does only shallow copy.*/
	Fixed(const Fixed& copy); 

	/* copy assignment operator:
	The main difference between Copy Constructor and Assignment Operator is that 
	the Copy constructor makes a new memory storage every time it is called 
	while the assignment operator does not make new memory storage. */
	Fixed& operator = (const Fixed& copy);

	int		getRawBits( void ) const;
	void	setRawBits( int const raw );
};


